# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# $schema: https://www.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
    cooldown:
      default-days: 5
      exclude:
        - mermaid
        - '@mermaid-js/*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
    cooldown:
      default-days: 5
    groups:
      actions:
        patterns:
          - "actions/*"
        update-types: ['minor', 'patch']
      docker:
        patterns:
          - "docker/*"
        update-types: ['minor', 'patch']
      codeql:
        # All CodeQL actions need to be on the exact same version
        patterns:
          - "github/codeql-action/*"
