categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
      - "feat"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: 📦 Dependency updates
    labels:
      - dependencies
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes
  $CHANGES

replacers:
  - search: "@dependabot-preview"
    replace: "@dependabot"
